version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - price-aggregator-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  exchange1:
    build:
      context: .
      dockerfile: mocks/Dockerfile
    command: ./mock_server 8081 exchange1
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - price-aggregator-network

  exchange2:
    build:
      context: .
      dockerfile: mocks/Dockerfile
    command: ./mock_server 8082 exchange2
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - price-aggregator-network

  exchange3:
    build:
      context: .
      dockerfile: mocks/Dockerfile
    command: ./mock_server 8083 exchange3
    ports:
      - "8083:8083"
    depends_on:
      - redis
    networks:
      - price-aggregator-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - price-aggregator-network
    environment:
      - AWS_REGION=us-west-2
    volumes:
      - ~/.aws:/root/.aws:ro 

networks:
  price-aggregator-network:
    driver: bridge