services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  exchange1:
    build:
      context: ./mock
    command: ["8081", "Exchange1"]
    ports:
      - "8081:8081"
    restart: always

  exchange2:
    build:
      context: ./mock
    command: ["8082", "Exchange2"]
    ports:
      - "8082:8082"
    restart: always

  exchange3:
    build:
      context: ./mock
    command: ["8083", "Exchange3"]
    ports:
      - "8083:8083"
    restart: always

  app:
    build:
      context: .
    environment:
      - REDIS_ADDR=redis:6379
      - EXCHANGE1_URL=http://exchange1:8081/mock/ticker
      - EXCHANGE2_URL=http://exchange2:8082/mock/ticker
      - EXCHANGE3_URL=http://exchange3:8083/mock/ticker
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - exchange1
      - exchange2
      - exchange3
    restart: always
    volumes:
      - ./symbols.csv:/app/symbols.csv

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./deploy/price_aggregator.json:/etc/grafana/provisioning/dashboards/price_aggregator.json
    restart: always
    depends_on:
      - prometheus